USE [master]

GO
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'TPS')
	DROP DATABASE TPS
GO
CREATE DATABASE TPS

GO
USE TPS
GO

CREATE TABLE [dbo].[Categories](
[CategoryID] [int] PRIMARY KEY IDENTITY(1,1) NOT NULL,
[CategoryName] [nvarchar](50) NOT NULL,
[Description] [ntext] NULL,
)

INSERT INTO [dbo].[Categories] ([CategoryName],[Description])
VALUES
('Men','What do gentlemen look for perfume for? Probably to smell good, be masculine and enhance their style, right ? Namperfume understands our gentlemen , brings to men decent, neat, attractive, sometimes overwhelmingly powerful scents, and certainly cannot forget the typical liberal dustiness of men.'),
('Women','Perfume from the early days was created to serve women, so it seems that in the world of scent, the choices for women are richer and more colorful. That"s why, namperfume always wants to bring beautiful ladies great options, from seductive, luxurious, powerful to gentle, innocent, and indispensable a bit of flirty sexiness. recline...'),
('Unisex','Unisex perfume is a perfume line suitable for all genders, whether men or women can use this product. Same perfume, but when men use it, they will become elegant. A girl who possesses adorable charms will become even more attractive.'),
('Giftset','Giftset - also known as gift set, is a collection of many different types of products. They are all highly applicable to serve work and daily life. All The products in the Giftset are all related to each other and have high aesthetics to bring satisfaction to the recipient.');

CREATE TABLE [dbo].[SubCategories](
[SubCategoryID] [int] PRIMARY KEY IDENTITY(1,1) NOT NULL,
[SubCategoryName] [nvarchar](255) NOT NULL,
[CategoryID] int NOT NULL,
FOREIGN KEY (CategoryID) REFERENCES [dbo].[Categories]([CategoryID])
)
INSERT INTO [dbo].[SubCategories] ([SubCategoryName],[CategoryID])
VALUES
('Citrus',1),
('Floral',1),
('Fresh',1),
('Fruity',1),
('Romantic',1),
('Spicy',1),
('Woody',1),
('Citrus',2),
('Floral',2),
('Fresh',2),
('Fruity',2),
('Romantic',2),
('Spicy',2),
('Woody',2),
('Citrus',3),
('Floral',3),
('Fresh',3),
('Fruity',3),
('Romantic',3),
('Spicy',3),
('Woody',3);


CREATE TABLE [dbo].[Roles] (
    roleID INT PRIMARY KEY IDENTITY(1,1),
    roleName NVARCHAR(50) NOT NULL UNIQUE
)
INSERT INTO [dbo].[Roles] (roleName) VALUES
('Admin'),
('Sale'),
('Marketing'),
('Customer');

CREATE TABLE [dbo].[Accounts](
[AccountID] [int] IDENTITY(1,1) PRIMARY KEY,
[FirstName] [nvarchar](50) NOT NULL,
[LastName] [nvarchar](50) NOT NULL,
[Password] [nvarchar](512) NOT NULL,
[Image] [nvarchar](50) NULL,
[Gender] int NOT NULL,
[BirthDay] date NOT NULL,
[Phone] [nvarchar](11) NOT NULL,
[Email] [nvarchar](50) NULL,
[Address] [nvarchar](225) NULL,
[Status] bit NOT NULL,
[CreateDate] date NOT NULL,
[RoleID] [int] NOT NULL,
FOREIGN KEY (roleID) REFERENCES [dbo].[Roles](roleID)
)



INSERT INTO [dbo].[Accounts] ([FirstName],[LastName],[Email],[Password],[Image],[Gender],[BirthDay],[Phone],[Address],[CreateDate],[RoleID],[Status]) 
VALUES
(N'Hà',N'Phạm','pna2906@gmai.com','123456','images/users/Ha.png',1,'2003-06-29','0862981785',N'Hà Nội','2024-05-24',1,1),
(N'Bích',N'Nguyễn','123@gmail.com','123456','images/users/Bich.png',1,'2003-11-01','0123456789',N'Hà Nội','2024-05-23',1,1),
(N'Hoàng',N'Nguyễn','123@gmai.com','123456','images/users/Hoang.png',1,'2003-06-29','0862981785',N'Hà Nội','2024-05-24',1,1),
(N'Trung',N'Hà','123@gmai.com','123456','images/users/Hoang.png',1,'2003-06-29','0862981785',N'Hà Nội','2024-05-24',2,1),
(N'Khánh',N'Nguyễn','123@gmai.com','123456','images/users/Hoang.png',1,'2003-06-29','0862981785',N'Hà Nội','2024-05-24',3,1);


CREATE TABLE [dbo].[Feedbacks] (
    fbID INT PRIMARY KEY IDENTITY(1,1),
    fbAccountID INT NOT NULL,
    fbProductID INT NOT NULL,
    fbStar INT NOT NULL,
    fbContent NVARCHAR(255) NULL,
    fbImage NVARCHAR(255) NULL,
    fbDate DATE NOT NULL,
    fbStatus INT NOT NULL,
    FOREIGN KEY (fbAccountID) REFERENCES [dbo].[Accounts](AccountID)
)
CREATE TABLE [dbo].[Brands] (
    [BrandID] INT PRIMARY KEY IDENTITY(1,1),
    [BrandName] NVARCHAR(100) NOT NULL UNIQUE,
    [Description] NVARCHAR(MAX)
)
INSERT INTO [dbo].[Brands]([BrandName],[Description])
VALUES
('GUCCI','Gucci perfume is one of the most revered brands in the world. Founded in the 1920s in Florence, Italy, Gucci has always understood that fashion and perfume are two inseparable things. The company offers clothes with modern, modern styles for both men and women. Gucci famous interlocking letter logo has become a fashion icon that is always seen in all of the company products, from bag collections, sportswear, seasonal high and thin heels to perfume bottles. Gucci perfumes have a variety of scents, from sensual and indulgent to sweet and fresh. Along with the company clothing and accessories lines, which have long become classic scents.'),
('CHANEL','Chanel is a famous perfume brand known for its elegance, sophistication and class. Chanel perfume products often have unique scents, combining natural ingredients. natural and synthetic to create unique and long-lasting scents.'),
('XERJOFF','Xerjoff is a famous high-end perfume brand with the perfect combination of craftsmanship and rare ingredients. Xerjoff perfume lines bring unique fragrance experiences. unique, complex and full of sophistication.'),
('LOUIS VUITTON', 'Louis Vuitton, famous for its luxury and class in fashion and accessories, also offers high-end perfume lines with delicate and unique scents. Louis Vuitton perfumes are Created by leading perfumers, using rare and high quality ingredients.'),
('DIOR','Dior is a famous brand in the field of perfume, with many iconic product lines. Dior perfume stands out with its sophisticated combination of high-quality ingredients, bringing the fragrance is diverse and rich.'),
('TOMMY HILFIGER','Tommy Hilfiger is a famous brand, not only in the fashion field but also in the perfume industry. Tommy Hilfiger perfumes often have a youthful, dynamic and fresh style.' ),
('ISSEY MIYAKE',N'Issey Miyake is a famous brand with modern, minimalist and sophisticated perfume lines. Issey Miyake perfumes often stand out with their fresh, elegant and creative, inspired by nature and natural elements.'),
('CREED', 'Creed is a high-end French perfume brand, famous for its handmade, sophisticated and luxurious perfume lines. Each Creed product is usually made from quality natural ingredients. high quality, providing a unique and long-lasting fragrance.'),
('YVES SAINT LAURENT (YSL)','Yves Saint Laurent (YSL) is a famous perfume brand, standing out with products that have a seductive, bold and modern style. YSL perfumes are often highly appreciated for the creativity in blending aromas, bringing unique and impressive scents.'),
('ARMAF','Armaf is a famous perfume brand with high quality products at affordable prices. Armaf perfumes often have diverse styles, from fresh to passionate, suitable for everyone. Suitable for many different tastes and occasions.'),
('ROJA PARFUMS', 'Roja Parfums is a high-end and luxurious perfume brand of perfume creator Roja Dove. Roja Parfums products are often known for their sophistication in the way they combine scents. materials, ensuring the highest quality and uniqueness. Each bottle of Roja Parfums perfume is often handmade and limited, creating works of art in the world of perfume.'),
('LE LABO','Le Labo is a high-end and unique perfume brand, famous for creating handmade and personalized products. Each bottle of Le Labo perfume is made in-house products, ensuring sophistication and quality. This brand focuses on using natural and high-quality ingredients, along with unique flavor blends.'),
('BVLGARI','Bvlgari is a renowned luxury brand known for its exquisite fragrances and perfumes. Founded in 1884 by jewelry manufacturer Sotirio Bulgari, the brand offers both bold and modern scents as well as timeless classics. Bvlgari’s master perfumers create high-quality fragrances that reflect elegance and refinement. Their Eau Parfumee collection includes captivating scents for both men and women, making Bvlgari a go-to choice for those seeking sophistication and allure '),
('VERSACE','Versace is an Italian luxury fashion company founded by Gianni Versace in 1978. Known for its audacious and unapologetic style, Versace fuses street fashion with high-end designs, resulting in bombastic and avant-garde creations. The iconic Versace logo draws inspiration from Greek mythology, featuring the figure of Medusa. Versace produces Italian-made ready-to-wear clothing, accessories, and haute couture under its Atelier Versace brand, and licenses its name to Luxottica for eyewear. Their distinctive style combines materials like metal, mesh, and leather, often painted in bright colors, celebrating individuality and sensuality . '),
('LANCOME','Lancôme is a perfume and cosmetics brand with its roots in the heart of European fashion, Paris. Founded by Armand Petitjean during a major economic crisis in the mid-1930s, Lancôme has epitomized beauty with a French accent for over 80 years. What began as a brand helmed by knowledgeable ambassadresses quickly grew to include a thousand boutiques across France. Lancôme’s legacy of expertise continues today with their team of industry-leading National Makeup Artists, led by Lisa Eldridge. ');
CREATE TABLE [dbo].[Products] (
    [ProductID] [INT] PRIMARY KEY IDENTITY(1,1),
    [SubCategoryID] [INT] NULL,
    [ProductName] [NVARCHAR](255) NOT NULL,
    [ProductCreateDate] DATE NOT NULL,
    [ProductDetailID] [INT] NULL,
    [ProductStatus] BIT NOT NULL,
    [ProductImageUrl] [nvarchar](255) NOT NULL,
    [OrderID] [INT] NULL,	
    [fbID] [INT] NULL,
	[BrandID] [int] NULL,
    FOREIGN KEY (SubCategoryID) REFERENCES [dbo].[SubCategories]([SubCategoryID]),
    FOREIGN KEY (fbID) REFERENCES [dbo].[Feedbacks]([fbID]),
	FOREIGN KEY (BrandID) REFERENCES [dbo].[Brands](BrandID),
)
INSERT INTO [dbo].[Products] (
[ProductName],
[ProductDetailID],
[ProductCreateDate],
[SubCategoryID],
[ProductStatus],
[BrandID],
[ProductImageUrl])
VALUES
--20 perfumes for Men
('XERJOFF CASAMORATI MEFISTO EDP FOR MEN',1,'2024-01-01',1,1,3,'images/Products/Men/1_0.jpg'),
('LOUIS VUITTON MÉTÉORE EDP FOR MEN',2,'2024-01-01',1,1,4,'images/Products/Men/2_0.jpg'),
('TOMMY ENDLESS BLUE FOR MEN',3,'2024-01-01',2,1,6,'images/Products/Men/3_0.jpg'),
('ISSEY MIYAKE LEAU DISSEY INTENSE FOR MEN',4,'2024-01-01',7,1,7,'images/Products/Men/4_0.jpg'),
('CREED AVENTUS EDP FOR MEN',5,'2024-01-01',4,1,8,'images/Products/Men/5_0.jpg'),
('DIOR SAUVAGE EDP FOR MEN',6,'2024-01-01',2,1,5,'images/Products/Men/6_0.jpg'),
('BLEU DE CHANEL EDP FOR MEN',7,'2024-01-01',7,1,2,'images/Products/Men/7_0.jpg'),
('YVES SAINT LAURENT LA NUIT DE L''HOMME EDT FOR MEN',8,'2024-01-01',6,1,9,'images/Products/Men/8_0.jpg'),
('VERSACE DYLAN BLUE POUR HOMME FOR MEN',9,'2024-01-01',2,1,14,'images/Products/Men/9_0.jpg'),
('ARMAF VENTANA POUR HOMME EDP FOR MEN',10,'2024-01-01',7,1,10,'images/Products/Men/10_0.jpg'),
('BVLGARI WOOD NEROLI EDP FOR MEN',11,'2024-01-01',7,1,13,'images/Products/Men/11_0.jpg'),
('VERSACE EAU FRAICHE EDT FOR MEN',12,'2024-01-01',7,1,14,'images/Products/Men/12_0.jpg'),
('GUCCI GUILTY ABSOLUTE POUR HOMME FOR MEN',13,'2024-01-01',7,1,1,'images/Products/Men/13_0.jpg'),
('YVES SAINT LAURENT Y EDP FOR MEN',14,'2024-01-01',2,1,9,'images/Products/Men/14_0.jpg'),
('ROJA ENIGMA POUR HOMME FOR MEN',15,'2024-01-01',5,1,11,'images/Products/Men/15_0.jpg'),
('BVLGARI SPLENDIDA JASMIN NOIR EDP FOR MEN',16,'2024-01-01',2,1,13,'images/Products/Men/16_0.jpg'),
('CHANEL ANTAEUS POUR HOMME EDT FOR MEN',17,'2024-01-01',6,1,2,'images/Products/Men/17_0.jpg'),
('DIOR HOMME SPORT EDT FOR MEN',18,'2024-01-01',7,1,5,'images/Products/Men/18_0.jpg'),
('VERSACE EROS FLAME FOR MEN',19,'2024-01-01',6,1,14,'images/Products/Men/19_0.jpg'),
('ISSEY MIYAKE NUIT DISSEY EDT FOR MEN',20,'2024-01-01',6,1,7,'images/Products/Men/20_0.jpg'),


--20 perfumes for Women
('CHANEL CHANCE EDP FOR WOMEN',21,'2024-01-01',9,1,2,'images/Products/Women/1_0.jpg'),
('DIOR JOY EDP FOR WOMEN',22,'2024-01-01',11,1,5,'images/Products/Women/2_0.jpg'),
('YSL LIBRE EDP FOR WOMEN',23,'2024-01-01',9,1,9,'images/Products/Women/3_0.jpg'),
('LOUIS VUITTON SPELL ON YOU EDP FOR WOMEN',24,'2024-01-01',9,1,4,'images/Products/Women/4_0.jpg'),
('CHANEL CHANCE EAU FRAICHE EDP FOR WOMEN',25,'2024-01-01',8,1,2,'images/Products/Women/5_0.jpg'),
('LANCOME LA VIE EST BELLE EN ROSE FOR WOMEN',26,'2024-01-01',11,1,15,'images/Products/Women/6_0.jpg'),
('LANCOME TRESOR LA NUIT EDP FOR WOMEN',27,'2024-01-01',9,1,15,'images/Products/Women/7_0.jpg'),
('LANCOME LA VIE EST BELLE EDP FOR WOMEN',28,'2024-01-01',11,1,15,'images/Products/Women/8_0.jpg'),
('GUCCI BLOOM AMBROSIA DI FIORI EDP FOR WOMEN',29,'2024-01-01',9,1,1,'images/Products/Women/9_0.jpg'),
('BVLGARI ROSE GOLDEA FOR WOMEN',30,'2024-01-01',9,1,13,'images/Products/Women/10_0.jpg'),
('ARMAF CLUB DE NUIT FOR WOMEN',31,'2024-01-01',11,1,10,'images/Products/Women/11_0.jpg'),
('GUCCI FLORA GORGEOUS GARDENIA EDP FOR WOMEN',32,'2024-01-01',9,1,1,'images/Products/Women/12_0.jpg'),
('TOMMY GIRL EDT FOR WOMEN',33,'2024-01-01',11,1,6,'images/Products/Women/13_0.jpg'),
('ROJA ELIXIR POUR FEMME FOR WOMEN',34,'2024-01-01',9,1,11,'images/Products/Women/14_0.jpg'),
('CHANEL COCO MADEMOISELLE EDP FOR WOMEN',35,'2024-01-01',9,1,2,'images/Products/Women/15_0.jpg'),
('LOUIS VUITTON MATIERE NOIRE FOR WOMEN',36,'2024-01-01',14,1,4,'images/Products/Women/16_0.jpg'),
('LOUIS VUITTON CALIFORNIA DREAM FOR WOMEN',37,'2024-01-01',11,1,4,'images/Products/Women/17_0.jpg'),
('GUCCI BLOOM EDP FOR WOMEN',38,'2024-01-01',9,1,1,'images/Products/Women/18_0.jpg'),
('CHANEL COCO NOIR FOR WOMEN',39,'2024-01-01',9,1,2,'images/Products/Women/19_0.jpg'),
('VERSACE DYLAN BLUE POUR FEMME EDP FOR WOMEN',40,'2024-01-01',11,1,14,'images/Products/Women/20_0.jpg'),


--20 perfumes for Unisex
('XERJOFF NAXOS EDP FOR UNISEX',41,'2024-01-01',13,1,3,'images/Products/Unisex/1_0.jpg'),
('ARMAF STERLING CLUB DE NUIT MILESTONE EDP FOR UNISEX',42,'2024-01-01',16,1,10,'images/Products/Unisex/2_0.jpg'),
('GUCCI A SONG FOR THE ROSE EDP FOR UNISEX',43,'2024-01-01',16,1,1,'images/Products/Unisex/3_0.jpg'),
('LE LABO THE NOIR 29 EDP FOR UNISEX',44,'2024-01-01',21,1,12,'images/Products/Unisex/4_0.jpg'),
('LOUIS VUITTON OMBRE NOMADE EDP FOR UNISEX',45,'2024-01-01',21,1,4,'images/Products/Unisex/5_0.jpg'),
('CREED SILVER MOUTAIN WATER FOR UNISEX',46,'2024-01-01',17,1,8,'images/Products/Unisex/6_0.jpg'),
('LE LABO BERGAMOTE 22 EDP FOR UNISEX',47,'2024-01-01',15,1,12,'images/Products/Unisex/7_0.jpg'),
('LE LABO SANTAL 33 FOR UNISEX',48,'2024-01-01',21,1,12,'images/Products/Unisex/8_0.jpg'),
('ROJA DOVE AMBER AOUND PARFUM FOR UNISEX',49,'2024-01-01',20,1,11,'images/Products/Unisex/9_0.jpg'),
('LOUIS VUITTON CACTUS GARDEN EDP FOR UNISEX',50,'2024-01-01',15,1,4,'images/Products/Unisex/10_0.jpg'),
('LOUIS VUITOTN SUN SONG EDP FOR UNISEX',51,'2024-01-01',15,1,4,'images/Products/Unisex/11_0.jpg'),
('ROJA DOVE MANHATTAN EDP FOR UNISEX',52,'2024-01-01',20,1,11,'images/Products/Unisex/12_0.jpg'),
('ROJA DOVE BURLINGTON 1819 PARFUM FOR UNISEX',53,'2024-01-01',15,1,11,'images/Products/Unisex/13_0.jpg'),
('XERJOFF ALEXANDRIA II FOR UNISEX',54,'2024-01-01',21,1,3,'images/Products/Unisex/14_0.jpg'),
('BVLGARI SPLENDIDA MAGNOLIA SENSUEL EDP FOR UNISEX',55,'2024-01-01',16,1,13,'images/Products/Unisex/15_0.jpg'),
('ARMAF CLUB DE NUIT UNTOLD EDP FOR UNISEX',56,'2024-01-01',16,1,10,'images/Products/Unisex/16_0.jpg'),
('GUCCI BLOOM ACQUA DI FIORI EDT',57,'2024-01-01',16,1,1,'images/Products/Unisex/17_0.jpg'),
('CHANEL GABRIELLE ESSENCE EDP',58,'2024-01-01',16,1,2,'images/Products/Unisex/18_0.jpg'),
('VERSACE YELLOW DIAMOND INTENSE EDP FOR UNISEX',59,'2024-01-01',16,1,14,'images/Products/Unisex/19_0.jpg'),
('CHANEL ALLURE HOMME SPORT COLOGNE FOR UNISEX',60,'2024-01-01',15,1,2,'images/Products/Unisex/20_0.jpg'),

--5 Giftset 
('SET YSL BLACK OPIUM EDP FOR GIFT SET',61,'2024-01-01',NULL,1,9,'images/Products/Giftset/1_0.jpg'),
('SET BVLGARI OMNIA FOR GIFT SET',62,'2024-01-01',NULL,1,13,'images/Products/Giftset/2_0.jpg'),
('SET OF 5 LANCOME PARIS PERFUMES FOR GIFT SET',63,'2024-01-01',NULL,1,15,'images/Products/Giftset/3_0.jpg'),
('BVLGARI OMNIA AMETHYSTE FOR GIFT SET',64,'2024-01-01',NULL,1,13,'images/Products/Giftset/4_0.jpg'),
('VERSACE BRIGHT CRYSTAL ABSOLU FOR GIFT SET',65,'2024-01-01',NULL,1,14,'images/Products/Giftset/5_0.jpg');

CREATE TABLE [dbo].[ProductFullDetail] (
    [ProductFullDetailID] [int] PRIMARY KEY IDENTITY(1,1),
    [pdProductID] [int] NOT NULL,
    [ProductDescription] [NVARCHAR](max) NULL,
    [ProductCreateDate] DATE NULL,
    [ProductStatus] BIT NOT NULL,
    [ProductSize] [NVARCHAR](max) NULL,
    [ProductPrice] [decimal](18, 2) NOT NULL,
    [ProductAvaiable] [int] NOT NULL
	FOREIGN KEY ([pdProductID]) REFERENCES [dbo].[Products]([ProductID])
)
INSERT INTO [dbo].[ProductFullDetail] (
[pdProductID],
[ProductDescription],
[ProductCreateDate],
[ProductStatus],
[ProductSize],
[ProductPrice],
[ProductAvaiable])
VALUES
--Details full for men
( 1, 'Inspired by the Italian coast, in 2009 the Xerjoff brand launched a perfume for men called Xerjoff Casamorati Mefisto EDP. This is one of the perfume bottles located in the famous and very popular Casamorati collection.', '2024-01-01', 1, '30ml', 50.00, 100),
( 1, 'Inspired by the Italian coast, in 2009 the Xerjoff brand launched a perfume for men called Xerjoff Casamorati Mefisto EDP. This is one of the perfume bottles located in the famous and very popular Casamorati collection.', '2024-01-01', 1, '100ml', 120.00, 100),
( 2, 'Louis Vuitton Météore EDP is part of Louis Vuitton "Les Parfum" collection just launched in 2020. As soon as it was released, this perfume bottle attracted attention. The idea of ​​boys with a luxurious and sophisticated design. Inspired by snow and ice crystals, the perfume bottle is designed with a round cylinder shape and soft rounded edges.', '2024-01-01', 1, '30ml', 60.00, 100),
( 2, 'Louis Vuitton Météore EDP is part of Louis Vuitton "Les Parfum" collection just launched in 2020. As soon as it was released, this perfume bottle attracted attention. The idea of ​​boys with a luxurious and sophisticated design. Inspired by snow and ice crystals, the perfume bottle is designed with a round cylinder shape and soft rounded edges.', '2024-01-01', 1, '100ml', 134.00, 100),
( 3, 'Tommy Endless Blue is a perfume line of Tommy Hilfiger for men, launched in 2017. This men''s perfume bottle features a harmonious scent between sweetness of Tonka Beans, the spiciness of black pepper and the peaceful scent of herbs with a spicy kick of cognac.', '2024-01-01', 1, '30ml', 30.00, 100),
( 3, 'Tommy Endless Blue is a perfume line of Tommy Hilfiger for men, launched in 2017. This men''s perfume bottle features a harmonious scent between sweetness of Tonka Beans, the spiciness of black pepper and the peaceful scent of herbs with a spicy kick of cognac.', '2024-01-01', 1, '100ml', 95.00, 100),
( 4, 'Issey Miyake L EAU D ISSEY Intense is a work of art as a men perfume by Issey Miyake, launched to create a fragrant experience. This fragrance is full of charm and depth. This is not simply a perfume, but also a story about emotions and the beauty of contrasts.', '2024-01-01', 1, '30ml', 46.00, 100),
( 4, 'Issey Miyake L EAU D ISSEY Intense is a work of art as a men perfume by Issey Miyake, launched to create a fragrant experience. This fragrance is full of charm and depth. This is not simply a perfume, but also a story about emotions and the beauty of contrasts.', '2024-01-01', 1, '100ml', 137.00, 100),
( 5, 'Creed Aventus - A name that is no longer strange to trendy scent followers. Appointed as the king of men perfume. For being at the forefront of creating a scent Citrus, easy to use but indescribably unique. Attractive with a luxurious and attractive scent, adding a bit of generosity and bravery. The perfume line is inspired by the dramatic life of King Napoleon symbolizes war, peace and romance.', '2024-01-01', 1, '30ml', 29.00, 100),
( 5, 'Creed Aventus - A name that is no longer strange to trendy scent followers. Appointed as the king of men perfume. For being at the forefront of creating a scent Citrus, easy to use but indescribably unique. Attractive with a luxurious and attractive scent, adding a bit of generosity and bravery. The perfume line is inspired by the dramatic life of King Napoleon symbolizes war, peace and romance.', '2024-01-01', 1, '100ml', 63.00, 100),
(6, 'Dior Sauvage EDP men''s perfume of the Christian Dior brand was launched in 2018, known as the version that continues the resounding success of the 2015 product line that made men "suffer". The scent of Dior Sauvage EDP is masculine, strong, attractive from everyday scents and conquers the most demanding people.', '2024-01-01', 1, '30ml', 75.00, 100),
(6, 'Dior Sauvage EDP men''s perfume of the Christian Dior brand was launched in 2018, known as the version that continues the resounding success of the 2015 product line that made men "suffer". The scent of Dior Sauvage EDP is masculine, strong, attractive from everyday scents and conquers the most demanding people.', '2024-01-01', 1, '100ml', 155.00, 100),
(7, 'Bleu De Chanel EDP men''s perfume is extremely popular, the scent is perfect and an absolute hit in that it suits all men and can be used at any time.', '2024-01-01', 1, '30ml', 85.00, 100),
(7, 'Bleu De Chanel EDP men''s perfume is extremely popular, the scent is perfect and an absolute hit in that it suits all men and can be used at any time.', '2024-01-01', 1, '100ml', 170.00, 100),
(8, 'Yves Saint Laurent La Nuit de L''Homme EDT offers a seductive and enchanting fragrance. The blend of spice notes such as cardamom, cedarwood, and lavender creates a masculine, strong scent that retains sophistication and elegance.','2024-01-01',1,'30ml',34.70,100),
(8, 'Yves Saint Laurent La Nuit de L''Homme EDT offers a seductive and enchanting fragrance. The blend of spice notes such as cardamom, cedarwood, and lavender creates a masculine, strong scent that retains sophistication and elegance.','2024-01-01',1,'100ml',104.50,100),
(9, 'Versace Dylan Blue Pour Homme is the perfect choice for those who love freshness and dynamism. The top notes of grapefruit, bergamot and seawater provide a refreshing feel, while the middle notes of fig leaves and the end notes of wood and aromatic resin make for the perfect and lasting balance.','2024-01-01',1,'30ml',45.00,100),
(9, 'Versace Dylan Blue Pour Homme is the perfect choice for those who love freshness and dynamism. The top notes of grapefruit, bergamot and seawater provide a refreshing feel, while the middle notes of fig leaves and the end notes of wood and aromatic resin make for the perfect and lasting balance.','2024-01-01',1,'100ml',130.00,100),
(10,'Armaf Ventana Pour Homme EDP is a passionate and attractive fragrance, ideal for special occasions. With early notes of bergamot, lemon and tangerine, combined with woody midst notes and end notes of vanilla and musk, this perfume gives confidence and charm to men.','2024-01-01',1,'30ml',52.00,100),
(10,'Armaf Ventana Pour Homme EDP is a passionate and attractive fragrance, ideal for special occasions. With early notes of bergamot, lemon and tangerine, combined with woody midst notes and end notes of vanilla and musk, this perfume gives confidence and charm to men.','2024-01-01',1,'100ml',160.00,100),
(11,'Wood Neroli is a floral scent, wood, musk for men, launched by perfume company Bvlgari in 2019. This is also the second scent in Bvlgari''s new collection, with the first edition entitled Wood Essence.','2024-01-01',1,'30ml',36.00,100),
(11,'Wood Neroli is a floral scent, wood, musk for men, launched by perfume company Bvlgari in 2019. This is also the second scent in Bvlgari''s new collection, with the first edition entitled Wood Essence.','2024-01-01',1,'10ml',94.00,100),
(12,'Versace Man Eau Fraiche for men is suitable for daytime, especially in summer when the weather is hot. Help boys stay fresh and refreshed with a cool and masculine scent.','2024-01-01',1,'30ml',32.00,100),
(12,'Versace Man Eau Fraiche for men is suitable for daytime, especially in summer when the weather is hot. Help boys stay fresh and refreshed with a cool and masculine scent.','2024-01-01',1,'100ml',103.00,100),
(13,'Gucci Guilty Absolute Pour Homme is a powerful and masculine fragrance that offers charm and mystery. With a combination of woody, amber and leather notes, this perfume creates a sense of charm and power.','2024-01-01',1,'30ml',25.50,100),
(13,'Gucci Guilty Absolute Pour Homme is a powerful and masculine fragrance that offers charm and mystery. With a combination of woody, amber and leather notes, this perfume creates a sense of charm and power.','2024-01-01',1,'100ml',82.50,100),
(14,'Yves Saint Laurent Y EDP is a modern and powerful fragrance that is ideal for confident and stylish men. The refreshing tip notes of citrus and ginger, combined with the middle notes from sage and the end notes from wood and amber, create a unique and lasting scent.','2024-01-01',1,'30ml',49.99,100),
(14,'Yves Saint Laurent Y EDP is a modern and powerful fragrance that is ideal for confident and stylish men. The refreshing tip notes of citrus and ginger, combined with the middle notes from sage and the end notes from wood and amber, create a unique and lasting scent.','2024-01-01',1,'100ml',139.99,100),
(15,'Roja Enigma Pour Homme is a complex and mysterious fragrance, ideal for special occasions. With a blend of bergamot, ginger, and cognac, combined with woody and tobacco notes, this perfume offers elegance and charm.','2024-01-01',1,'30ml',35.70,100),
(15,'Roja Enigma Pour Homme is a complex and mysterious fragrance, ideal for special occasions. With a blend of bergamot, ginger, and cognac, combined with woody and tobacco notes, this perfume offers elegance and charm.','2024-01-01',1,'100ml',103.20,100),
(16,'Bvlgari Splendida Jasmin Noir EDP is an elegant and delicate fragrance, with early notes of jasmine and almond, middle notes of wood and end notes of musk and vanilla, creating a masculine, luxurious and attractive scent.','2024-01-01',1,'30ml',27.30,100),
(16,'Bvlgari Splendida Jasmin Noir EDP is an elegant and delicate fragrance, with early notes of jasmine and almond, middle notes of wood and end notes of musk and vanilla, creating a masculine, luxurious and attractive scent.','2024-01-01',1,'100ml',92.50,100),
(17,'Chanel Antaeus Pour Homme EDT is a strong and masculine fragrance, with a combination of woody, amber and spice notes. This fragrance gives confidence and strength, ideal for important occasions and special evenings.','2024-01-01',1,'30ml',43.20,100),
(17,'Chanel Antaeus Pour Homme EDT is a strong and masculine fragrance, with a combination of woody, amber and spice notes. This fragrance gives confidence and strength, ideal for important occasions and special evenings.','2024-01-01',1,'100ml',139.99,100),
(18,'Dior Homme Sport EDT is a fresh and active fragrance, ideal for active and sporting days. The top notes of citrus and ginger, combined with the middle notes from sage and the last notes from wood and musk, create a masculine and refreshing scent.','2024-01-01',1,'30ml',28.90,100),
(18,'Dior Homme Sport EDT is a fresh and active fragrance, ideal for active and sporting days. The top notes of citrus and ginger, combined with the middle notes from sage and the last notes from wood and musk, create a masculine and refreshing scent.','2024-01-01',1,'100ml',94.90,100),
(19,'Versace Eros Flame is a passionate and seductive fragrance, with a blend of bergamot, lemon and tangerine notes, combined with woody and final notes from vanilla and musk. This perfume gives confidence and charisma, ideal for special occasions.','2024-01-01',1,'30ml',35.60,100),
(19,'Versace Eros Flame is a passionate and seductive fragrance, with a blend of bergamot, lemon and tangerine notes, combined with woody and final notes from vanilla and musk. This perfume gives confidence and charisma, ideal for special occasions.','2024-01-01',1,'100ml',135.00,100),
(20,'Issey Miyake Nuit d''Issey EDT is a mysterious and enchanting fragrance, with a combination of woody, amber and spice notes. This fragrance gives confidence and charm, ideal for evenings and important occasions.','2024-01-01',1,'30ml',34.00,100),
(20,'Issey Miyake Nuit d''Issey EDT is a mysterious and enchanting fragrance, with a combination of woody, amber and spice notes. This fragrance gives confidence and charm, ideal for evenings and important occasions.','2024-01-01',1,'100ml',104.00,100),

--Details full for women

( 21, 'Chanel Chance EDP has been famous for many years, Chanel is sought after and used by many people because of its classy scent. Chanel Chance Eau De Parfum is one of the perfume lines most sought after by women, including me.', '2024-01-01', 1, '30ml', 70.00, 100),
( 21, 'Chanel Chance EDP has been famous for many years, Chanel is sought after and used by many people because of its classy scent. Chanel Chance Eau De Parfum is one of the perfume lines most sought after by women, including me.', '2024-01-01', 1, '100ml', 235.00, 100),
( 22, 'Dior Joy is a work that Dior has cherished for a long time, but has just released it. A new scent, completely different from previous perfumes. If these scents The previous scent was classic and elegant. Dior Joy is a scent full of joy and happiness that Dior wants to send to women.', '2024-01-01', 1, '30ml', 25.00, 100),
( 22, 'Dior Joy is a work that Dior has cherished for a long time, but has just released it. A new scent, completely different from previous perfumes. If these scents The previous scent was classic and elegant. Dior Joy is a scent full of joy and happiness that Dior wants to send to women.', '2024-01-01', 1, '100ml', 73.00, 100),
( 23, 'YSL Libre is a women perfume product line of high-end fashion house Yves Saint Laurent launched in 2019. YSL Libre belongs to the oriental scent group for women and is Created by two mixologists Anne Flipo and Carlos Benaim, Libre means "freedom" in French, inspired by the desire for freedom of independent, luxurious and sexy women.', '2024-01-01', 1, '30ml', 60.00, 100),
( 23, 'YSL Libre is a women perfume product line of high-end fashion house Yves Saint Laurent launched in 2019. YSL Libre belongs to the oriental scent group for women and is Created by two mixologists Anne Flipo and Carlos Benaim, Libre means "freedom" in French, inspired by the desire for freedom of independent, luxurious and sexy women.', '2024-01-01', 1, '100ml', 118.00, 100),
( 24, 'Louis Vuitton Spell On You EDP is a high-end women perfume product from the famous fashion brand Louis Vuitton. Launched in 2021, Spell On You promises is a safe choice for every girl because of its fresh, delicate, gentle scent.', '2024-01-01', 1, '30ml', 52.00, 100),
( 24, 'Louis Vuitton Spell On You EDP is a high-end women perfume product from the famous fashion brand Louis Vuitton. Launched in 2021, Spell On You promises is a safe choice for every girl because of its fresh, delicate, gentle scent.', '2024-01-01', 1, '100ml', 149.00, 100),
( 25, 'Chance Eau Fraiche captivates the world with its playful, lively and sparkling fragrance. Recently, Chanel launched a new line of women perfume Chance Eau Fraiche - brilliant Brilliant and elegant. A new opportunity is at hand.', '2024-01-01', 1, '30ml', 83.00, 100),
( 25, 'Chance Eau Fraiche captivates the world with its playful, lively and sparkling fragrance. Recently, Chanel launched a new line of women perfume Chance Eau Fraiche - brilliant Brilliant and elegant. A new opportunity is at hand.', '2024-01-01', 1, '100ml', 235.00, 100),
(26,  'Lancome La Vie Est Belle En Rose is a fresh and radiant fragrance for women. The top notes of red berries and bergamot provide freshness, while the middle notes from rose and peony add femininity and tenderness. The last scent of musk and wood creates a warm and lasting feeling, helping you always feel confident and happy.', '2024-01-01', 1, '30ml', 56.60, 100),
(26,' Lancome La Vie Est Belle En Rose is a fresh and radiant fragrance for women. The top notes of red berries and bergamot provide freshness, while the middle notes from rose and peony add femininity and tenderness. The last scent of musk and wood creates a warm and lasting feeling, helping you always feel confident and happy.','2024-01-01', 1, '100ml', 167.90, 100),
(27,' Lancome Tresor La Nuit EDP is a seductive and mysterious fragrance for women. With top notes from raspberries and pears, middle notes from black roses and vanilla orchids, along with final notes of woody and resinous, this perfume offers an enchanting charm, ideal for special evenings.','2024-01-01', 1, '30ml', 52.00, 100),
(27,' Lancome Tresor La Nuit EDP is a seductive and mysterious fragrance for women. With top notes from raspberries and pears, middle notes from black roses and vanilla orchids, along with final notes of woody and resinous, this perfume offers an enchanting charm, ideal for special evenings.','2024-01-01', 1, '100ml', 149.00, 100),
(28,'Lancome La Vie Est Belle EDP is a sweet and elegant fragrance for women. The top notes of pears and black currants, combined with mid-notes from irises, jasmine and orange blossoms, and the final notes of nougat beans, tonka beans and vanilla, create a perfect and enticing scent that brings a sense of happiness and fulfillment.','2024-01-01', 1, '30ml', 52.00, 100),
(28,'Lancome La Vie Est Belle EDP is a sweet and elegant fragrance for women. The top notes of pears and black currants, combined with mid-notes from irises, jasmine and orange blossoms, and the final notes of nougat beans, tonka beans and vanilla, create a perfect and enticing scent that brings a sense of happiness and fulfillment.','2024-01-01', 1, '100ml', 149.00, 100),
(29,' Gucci Bloom Ambrosia di Fiori EDP is a fresh and luxurious floral fragrance. The top notes of jasmine and lily, combined with the middle notes from magnolia and the end notes of Damascena roses, create a feminine and seductive scent, ideal for special occasions.','2024-01-01', 1, '30ml', 52.00, 100),
(29,' Gucci Bloom Ambrosia di Fiori EDP is a fresh and luxurious floral fragrance. The top notes of jasmine and lily, combined with the middle notes from magnolia and the end notes of Damascena roses, create a feminine and seductive scent, ideal for special occasions.','2024-01-01', 1, '100ml', 149.00, 100),
(30,'Bvlgari Rose Goldea EDP is a passionate and noble fragrance for women. With a combination of rose, musk and amber notes, this perfume offers a feminine, elegant and seductive scent, ideal for romantic evenings or important events.','2024-01-01', 1, '30ml', 52.00, 100),
(30,'Bvlgari Rose Goldea EDP is a passionate and noble fragrance for women. With a combination of rose, musk and amber notes, this perfume offers a feminine, elegant and seductive scent, ideal for romantic evenings or important events.','2024-01-01', 1, '100ml', 149.00, 100),
(31,'Armaf Club de Nuit for Women is a sweet and seductive fragrance, with early notes from bergamot, grapefruit and peach, middle notes from rose, geranium and jasmine, and final notes of vanilla, musk and amber. This perfume gives confidence and charisma, ideal for every occasion.','2024-01-01', 1, '30ml', 52.00, 100),
(31,'Armaf Club de Nuit for Women is a sweet and seductive fragrance, with early notes from bergamot, grapefruit and peach, middle notes from rose, geranium and jasmine, and final notes of vanilla, musk and amber. This perfume gives confidence and charisma, ideal for every occasion.','2024-01-01', 1, '100ml', 149.00, 100),
(32,' Gucci Flora Gorgeous Gardenia EDP is a refreshing and feminine fragrance, with notes starting from red berries and pears, middle notes from jasmine and orchids, and final notes from sugar and patchouli. This perfume feels fresh and energetic, ideal for summer days.','2024-01-01', 1, '30ml', 52.00, 100),
(32,' Gucci Flora Gorgeous Gardenia EDP is a refreshing and feminine fragrance, with notes starting from red berries and pears, middle notes from jasmine and orchids, and final notes from sugar and patchouli. This perfume feels fresh and energetic, ideal for summer days.','2024-01-01', 1, '100ml', 149.00, 100),
(33,'Tommy Girl EDT is a fresh and active fragrance for women. The top notes of citrus, mint and black currant, combined with notes from rose, lily and orange blossom, and the last notes of sandalwood and musk, create a refreshing and youthful scent, ideal for active days.','2024-01-01', 1, '30ml', 52.00, 100),
(33,'Tommy Girl EDT is a fresh and active fragrance for women. The top notes of citrus, mint and black currant, combined with notes from rose, lily and orange blossom, and the last notes of sandalwood and musk, create a refreshing and youthful scent, ideal for active days.','2024-01-01', 1, '100ml', 149.00, 100),
(34,' Roja Elixir Pour Femme is a luxurious and seductive fragrance, with notes starting from bergamot, middle notes from jasmine, rose and orange blossom, and final notes from sandalwood, musk and vanilla. This perfume offers femininity and nobility, ideal for special occasions.','2024-01-01', 1, '30ml', 52.00, 100),
(34,' Roja Elixir Pour Femme is a luxurious and seductive fragrance, with notes starting from bergamot, middle notes from jasmine, rose and orange blossom, and final notes from sandalwood, musk and vanilla. This perfume offers femininity and nobility, ideal for special occasions.','2024-01-01', 1, '100ml', 149.00, 100),
(35,' Chanel Coco Mademoiselle EDP is an elegant and sensual fragrance for women. Early notes from citrus and grapefruit, combined with notes from rose and jasmine, and final notes from patchouli, vanilla and musk, create a seductive and delicate scent, ideal for every occasion.','2024-01-01', 1, '30ml', 52.00, 100),
(35,' Chanel Coco Mademoiselle EDP is an elegant and sensual fragrance for women. Early notes from citrus and grapefruit, combined with notes from rose and jasmine, and final notes from patchouli, vanilla and musk, create a seductive and delicate scent, ideal for every occasion.','2024-01-01', 1, '100ml', 149.00, 100),
(36,' Louis Vuitton Matière Noire EDP is a mysterious and alluring fragrance for women. The first notes from black currants and raspberries, combined with notes from rose and jasmine, and the last notes from wood and amber, create a luxurious and enchanting scent.','2024-01-01', 1, '30ml', 52.00, 100),
(36,' Louis Vuitton Matière Noire EDP is a mysterious and alluring fragrance for women. The first notes from black currants and raspberries, combined with notes from rose and jasmine, and the last notes from wood and amber, create a luxurious and enchanting scent.','2024-01-01', 1, '100ml', 149.00, 100),
(37,' Louis Vuitton California Dream EDP is a refreshing and romantic fragrance, with notes starting from mandarins and bergamot, mid-notes from pear and magnolia, and final notes from musk and sandalwood. This perfume gives a feeling of freedom and freedom, ideal for summer days.','2024-01-01', 1, '30ml', 52.00, 100),
(37,' Louis Vuitton California Dream EDP is a refreshing and romantic fragrance, with notes starting from mandarins and bergamot, mid-notes from pear and magnolia, and final notes from musk and sandalwood. This perfume gives a feeling of freedom and freedom, ideal for summer days.','2024-01-01', 1, '100ml', 149.00, 100),
(38,' Gucci Bloom EDP is a fresh and elegant floral fragrance for women. The first notes from jasmine and lily, combined with the middle notes from orange blossom and the last from magnolia, create a feminine and seductive scent, ideal for every occasion.','2024-01-01', 1, '30ml', 52.00, 100),
(38,' Gucci Bloom EDP is a fresh and elegant floral fragrance for women. The first notes from jasmine and lily, combined with the middle notes from orange blossom and the last from magnolia, create a feminine and seductive scent, ideal for every occasion.','2024-01-01', 1, '100ml', 149.00, 100),
(39,'Chanel Coco Noir EDP is a powerful and seductive fragrance for women. The first notes from bergamot and grapefruit, combined with notes from jasmine and rose, and the last notes from patchouli, musk and amber, create a luxurious and mysterious scent.','2024-01-01', 1, '30ml', 52.00, 100),
(39,'Chanel Coco Noir EDP is a powerful and seductive fragrance for women. The first notes from bergamot and grapefruit, combined with notes from jasmine and rose, and the last notes from patchouli, musk and amber, create a luxurious and mysterious scent.','2024-01-01', 1, '100ml', 149.00, 100),
(40,' Versace Dylan Blue Pour Femme EDP is a fresh and active fragrance for women. The first notes from black currants and green apples, combined with notes from rose and jasmine, and final notes from wood and musk, create a feminine and modern scent, ideal for every occasion.','2024-01-01', 1, '30ml', 52.00, 100),
(40,' Versace Dylan Blue Pour Femme EDP is a fresh and active fragrance for women. The first notes from black currants and green apples, combined with notes from rose and jasmine, and final notes from wood and musk, create a feminine and modern scent, ideal for every occasion.','2024-01-01', 1, '100ml', 149.00, 100),


--Details full for unisex

( 41, 'Xerjoff Naxos EDP perfume is a unisex perfume line in the special collection of the Xerjoff brand. Launched in 2015, inspired by the essence of beauty. An island located in the middle of the Mediterranean Sea, Sicily.', '2024-01-01', 1, '30ml', 47.00, 100),
( 41, 'Xerjoff Naxos EDP perfume is a unisex perfume line in the special collection of the Xerjoff brand. Launched in 2015, inspired by the essence of beauty. An island located in the middle of the Mediterranean Sea, Sicily.', '2024-01-01', 1, '100ml', 134.00, 100),
( 42, 'Armaf Sterling Club De Nuit Milestone EDP perfume is the best-selling product line of Armaf perfume with a sweet and modern scent, a delicate blend of unique scent notes.', '2024-01-01', 1, '30ml', 39.00, 100),
( 42, 'Armaf Sterling Club De Nuit Milestone EDP perfume is the best-selling product line of Armaf perfume with a sweet and modern scent, a delicate blend of unique scent notes.', '2024-01-01', 1, '100ml', 119.00, 100),
( 43, 'In 2019, the Gucci brand launched the Gucci A Song For The Rose EDP perfume line, this is a unisex perfume for both men and women. Distilled scent From the floral scent group thyme creates a sweet and seductive scent.', '2024-01-01', 1, '30ml', 17.00, 100),
( 43, 'In 2019, the Gucci brand launched the Gucci A Song For The Rose EDP perfume line, this is a unisex perfume for both men and women. Distilled scent From the floral scent group thyme creates a sweet and seductive scent.', '2024-01-01', 1, '100ml', 59.00, 100),
( 44, 'Like other perfume lines of the Le Labo brand, the Le Labo The Noir 29 EDP perfume line has a minimalist, stylish bottle design. to a luxurious, sophisticated feeling. The perfume bottle is made of transparent glass, the color of the perfume inside can be seen. In particular, the owner of this perfume bottle can print his or her name on it sticker, this represents the personalization of the product, bringing a new and unique experience to customers.', '2024-01-01', 1, '30ml', 73.00, 100),
( 44, 'Like other perfume lines of the Le Labo brand, the Le Labo The Noir 29 EDP perfume line has a minimalist, stylish bottle design. to a luxurious, sophisticated feeling. The perfume bottle is made of transparent glass, the color of the perfume inside can be seen. In particular, the owner of this perfume bottle can print his or her name on it sticker, this represents the personalization of the product, bringing a new and unique experience to customers.', '2024-01-01', 1, '100ml', 225.00, 100),
( 45, 'Are you looking for a perfume line for both women and men with a truly luxurious scent as well as making an impression at the first moment? Then Louis Vuitton Ombre Nomade EDP is the right choice right now. This is a unisex perfume line from the luxury brand Louis Vuitton.', '2024-01-01', 1, '30ml', 36.00, 100),
( 45, 'Are you looking for a perfume line for both women and men with a truly luxurious scent as well as making an impression at the first moment? Then Louis Vuitton Ombre Nomade EDP is the right choice right now. This is a unisex perfume line from the luxury brand Louis Vuitton.', '2024-01-01', 1, '100ml', 106.00, 100),
(46,'Creed Silver Mountain Water is a fresh and pure fragrance for both men and women. The top notes from bergamot and black currants provide refreshment, while the middle notes from green tea and violets create elegance and sophistication. The last incense from musk and sandalwood helps retain the scent for a long time, giving it a feeling of freshness and energy.','2024-01-01', 1, '30ml', 36.00, 100),
(46,'Creed Silver Mountain Water is a fresh and pure fragrance for both men and women. The top notes from bergamot and black currants provide refreshment, while the middle notes from green tea and violets create elegance and sophistication. The last incense from musk and sandalwood helps retain the scent for a long time, giving it a feeling of freshness and energy.','2024-01-01', 1, '100ml', 106.00, 100),
(47,'Le Labo Bergamote 22 is a fresh and radiant fragrance with early notes from bergamot and grapefruit. The middle notes from orange blossom and vetiver add subtlety, while the final notes from musk and cedarwood provide a warm and pleasant feeling. This is perfect for both men and women on every occasion, from work to dates.','2024-01-01', 1, '30ml', 36.00, 100),
(47,'Le Labo Bergamote 22 is a fresh and radiant fragrance with early notes from bergamot and grapefruit. The middle notes from orange blossom and vetiver add subtlety, while the final notes from musk and cedarwood provide a warm and pleasant feeling. This is perfect for both men and women on every occasion, from work to dates.','2024-01-01', 1, '100ml', 106.00, 100),
(48,'Le Labo Santal 33 is a distinctive and seductive fragrance with heads from sandalwood and pepper. The middle notes from violets and cardamom make it unique, while the final notes from musk and amber provide warmth and appeal. This is the ideal choice for both men and women on special occasions.','2024-01-01', 1, '30ml', 36.00, 100),
(48,'Le Labo Santal 33 is a distinctive and seductive fragrance with heads from sandalwood and pepper. The middle notes from violets and cardamom make it unique, while the final notes from musk and amber provide warmth and appeal. This is the ideal choice for both men and women on special occasions.','2024-01-01', 1, '100ml', 106.00, 100),
(49,'Roja Dove Amber Aoud Parfum is a luxurious and noble fragrance with notes from lemon and bergamot. The middle notes from rose and saffron stigmas combine with final notes from agarwood and amber, providing warmth and charm. This is a great choice for both men and women on important occasions.','2024-01-01', 1, '30ml', 36.00, 100),
(49,'Roja Dove Amber Aoud Parfum is a luxurious and noble fragrance with notes from lemon and bergamot. The middle notes from rose and saffron stigmas combine with final notes from agarwood and amber, providing warmth and charm. This is a great choice for both men and women on important occasions.','2024-01-01', 1, '100ml', 106.00, 100),
(50,'Louis Vuitton Cactus Garden EDP is a refreshing and liberal fragrance with notes from bergamot and green tea. The middle notes from vetiver and ginger provide freshness and refreshment, while the final notes from musk create a sense of freedom and dynamism. This is perfect for summer days.','2024-01-01', 1, '30ml', 36.00, 100),
(50,'Louis Vuitton Cactus Garden EDP is a refreshing and liberal fragrance with notes from bergamot and green tea. The middle notes from vetiver and ginger provide freshness and refreshment, while the final notes from musk create a sense of freedom and dynamism. This is perfect for summer days.','2024-01-01', 1, '100ml', 106.00, 100),
(51,'Louis Vuitton Sun Song EDP is a cheerful and radiant fragrance with top notes from orange and lemon. The middle notes from orange blossom and jasmine create elegance, while the last from musk provides a pleasant and soothing feel. This is a great choice for both men and women on sunny days.','2024-01-01', 1, '30ml', 36.00, 100),
(51,'Louis Vuitton Sun Song EDP is a cheerful and radiant fragrance with top notes from orange and lemon. The middle notes from orange blossom and jasmine create elegance, while the last from musk provides a pleasant and soothing feel. This is a great choice for both men and women on sunny days.','2024-01-01', 1, '100ml', 106.00, 100),
(52,'Roja Dove Manhattan EDP is a luxurious and modern fragrance with notes from bergamot and tangerine. The middle notes from jasmine and rose combine with the final notes from sandalwood and musk, providing charm and elegance. This is the ideal choice for both men and women on special occasions.','2024-01-01', 1, '30ml', 36.00, 100),
(52,'Roja Dove Manhattan EDP is a luxurious and modern fragrance with notes from bergamot and tangerine. The middle notes from jasmine and rose combine with the final notes from sandalwood and musk, providing charm and elegance. This is the ideal choice for both men and women on special occasions.','2024-01-01', 1, '100ml', 106.00, 100),
(53,'Roja Dove Burlington 1819 Parfum is a complex and noble fragrance with heads from bergamot, lemon and grapefruit. The middle notes from rose and jasmine, and the final notes from amber and sandalwood, provide elegance and appeal. This is a great choice for both men and women on important occasions.','2024-01-01', 1, '30ml', 36.00, 100),
(53,'Roja Dove Burlington 1819 Parfum is a complex and noble fragrance with heads from bergamot, lemon and grapefruit. The middle notes from rose and jasmine, and the final notes from amber and sandalwood, provide elegance and appeal. This is a great choice for both men and women on important occasions.','2024-01-01', 1, '100ml', 106.00, 100),
(54,'Xerjoff Alexandria II is a strong and delicate fragrance with top notes from apple and cinnamon. The notes between rose and sandalwood combine with the final notes from vanilla and musk, creating charm and elegance. This is the ideal choice for both men and women on important occasions.','2024-01-01', 1, '30ml', 36.00, 100),
(54,'Xerjoff Alexandria II is a strong and delicate fragrance with top notes from apple and cinnamon. The notes between rose and sandalwood combine with the final notes from vanilla and musk, creating charm and elegance. This is the ideal choice for both men and women on important occasions.','2024-01-01', 1, '100ml', 106.00, 100),
(55,'Bvlgari Splendida Magnolia Sensuel EDP is a sweet and delicate fragrance with top notes from mandarins and bergamot. The middle notes from magnolia and jasmine, and the final notes from vanilla and musk, provide elegance and charm. This is the perfect option for both men and women on any occasion.','2024-01-01', 1, '30ml', 36.00, 100),
(55,'Bvlgari Splendida Magnolia Sensuel EDP is a sweet and delicate fragrance with top notes from mandarins and bergamot. The middle notes from magnolia and jasmine, and the final notes from vanilla and musk, provide elegance and charm. This is the perfect option for both men and women on any occasion.','2024-01-01', 1, '100ml', 106.00, 100),
(56,'Armaf Club de Nuit Untold EDP is a passionate and attractive fragrance with heads from bergamot and black currants. The middle notes from jasmine and rose combine with the final notes from musk and sandalwood, providing confidence and charm. This is the ideal choice for both men and women on special occasions.','2024-01-01', 1, '30ml', 36.00, 100),
(56,'Armaf Club de Nuit Untold EDP is a passionate and attractive fragrance with heads from bergamot and black currants. The middle notes from jasmine and rose combine with the final notes from musk and sandalwood, providing confidence and charm. This is the ideal choice for both men and women on special occasions.','2024-01-01', 1, '100ml', 106.00, 100),
(57,'Gucci Bloom Acqua di Fiori EDT is a refreshing and elegant fragrance with top notes from black currants and pears. The middle incense from jasmine and lily, and the last from musk and sandalwood, create femininity and charm. This is the perfect option for both men and women on any occasion.','2024-01-01', 1, '30ml', 36.00, 100),
(57,'Gucci Bloom Acqua di Fiori EDT is a refreshing and elegant fragrance with top notes from black currants and pears. The middle incense from jasmine and lily, and the last from musk and sandalwood, create femininity and charm. This is the perfect option for both men and women on any occasion.','2024-01-01', 1, '100ml', 106.00, 100),
(58,'Chanel Gabrielle Essence EDP is a sweet and delicate fragrance with heads from mandarins and bergamot. The middle notes from jasmine and orange blossom, and the final notes from musk and sandalwood, bring elegance and charm. This is a great choice for both men and women on important occasions.','2024-01-01', 1, '30ml', 36.00, 100),
(58,'Chanel Gabrielle Essence EDP is a sweet and delicate fragrance with heads from mandarins and bergamot. The middle notes from jasmine and orange blossom, and the final notes from musk and sandalwood, bring elegance and charm. This is a great choice for both men and women on important occasions.','2024-01-01', 1, '100ml', 106.00, 100),
(59,'Versace Yellow Diamond Intense EDP is a refreshing and vibrant fragrance with notes from lemon and bergamot. The middle notes from orange blossom and jasmine, and the last from musk and amber, create elegance and charm. This is the ideal option for both men and women on all occasions.','2024-01-01', 1, '30ml', 36.00, 100),
(59,'Versace Yellow Diamond Intense EDP is a refreshing and vibrant fragrance with notes from lemon and bergamot. The middle notes from orange blossom and jasmine, and the last from musk and amber, create elegance and charm. This is the ideal option for both men and women on all occasions.','2024-01-01', 1, '100ml', 106.00, 100),
(60,'Chanel Allure Homme Sport Cologne is a refreshing and dynamic fragrance with top notes from citrus and grapefruit. The middle notes from jasmine and rose, and the final notes from musk and sandalwood, create refreshment and charm. This is perfect for both men and women on active days.','2024-01-01', 1, '30ml', 36.00, 100),
(60,'Chanel Allure Homme Sport Cologne is a refreshing and dynamic fragrance with top notes from citrus and grapefruit. The middle notes from jasmine and rose, and the final notes from musk and sandalwood, create refreshment and charm. This is perfect for both men and women on active days.','2024-01-01', 1, '100ml', 106.00, 100),

--Details full for gift set

( 61, 'YSL Black Opium Eau De Parfum Christmas 2021 gift set, the new perfume line was announced as a classic rocknroll performance highlighting the magical, mysterious aspect of the YSL brand. Perfumers Nathalie Lorson and MarieSalamagne, collaborated with Olivier Cresp and Honorine Blanc to create this scent. YSL Balck Opium is Yves Saint Laurent first coffee-flower scent. The energy of black coffee dominates the entire fragrance of white flowers with assertive femininity accented by pink pepper and pear in the background.', '2024-01-01', 1, NULL, 100.00, 50),
( 62, 'BVLGari set of 3 bottles of 15ml includes 3 typical fragrances of the Bvlgari Omnia collection with 3 different styles and personalities gathered in the Bvlgari Omnia gift set so girls can experience the feelings about different scents. Bvlgari Omnia Coral EDT perfume 15ml Bvlgari Omnia Crystalline EDT perfume 15ml Bvlgari Omnia Amethyste EDT Perfume 15ml With a sophisticated, seductive and easy-to-use style, this collection will be a great choice when girls go to work or go out or picnic.', '2024-01-01', 1, NULL, 150.00, 50),
( 63, 'Set of 5 Lancome perfumes includes: Lancome Hypnose Eau de Parfum 5ml Lancome Tresor Eau de Parfum 7.5ml Lancome La vie est belle Eau de Parfum 4ml Lancome Miracle Eau de Parfum 5ml Lancome Tresor in Love Eau de Parfum 5ml', '2024-01-01', 1, NULL, 185.00, 50),
( 64, 'BVLGARI Omnia Amethyste Gift Set', '2024-01-01', 1, NULL, 212.00, 50),
( 65, 'Versace Absolute Gift Set 4 items: Versace Bright Crystal Absolu EDP 90ml perfume Versace Bright Crystal Absolu EDP 10ml Versace Perfumed Body Lotion 100ml Versace Perfumed Shower Gel 100ml', '2024-01-01', 1, NULL, 139.00, 50);

CREATE TABLE [dbo].[ProductDetailImages] (
    [ImageID] INT PRIMARY KEY IDENTITY(1,1),
    [ProductFullDetailID] INT NOT NULL,
    [ImageUrl] NVARCHAR(255) NOT NULL,
    FOREIGN KEY (ProductFullDetailID) REFERENCES [dbo].[ProductFullDetail]([ProductFullDetailID])
)
INSERT INTO [dbo].[ProductDetailImages] ([ProductFullDetailID], [ImageUrl])
VALUES
--Images of product men details 
(1, 'images/Products/Men/1_1.jpg'),
(1, 'images/Products/Men/1_2.jpg'),
(1, 'images/Products/Men/1_3.jpg'),
(2, 'images/Products/Men/2_1.jpg'),
(2, 'images/Products/Men/2_2.jpg'),
(2, 'images/Products/Men/2_3.jpg'),
(3, 'images/Products/Men/3_1.jpg'),
(3, 'images/Products/Men/3_2.jpg'),
(3, 'images/Products/Men/3_3.jpg'),
(4, 'images/Products/Men/4_1.jpg'),
(4, 'images/Products/Men/4_2.jpg'),
(4, 'images/Products/Men/4_3.jpg'),
(5, 'images/Products/Men/5_1.jpg'),
(5, 'images/Products/Men/5_2.jpg'),
(5, 'images/Products/Men/5_3.jpg'),
(6, 'images/Products/Men/6_1.jpg'),
(6, 'images/Products/Men/6_2.jpg'),
(6, 'images/Products/Men/6_3.jpg'),
(7, 'images/Products/Men/7_1.jpg'),
(7, 'images/Products/Men/7_2.jpg'),
(7, 'images/Products/Men/7_3.jpg'),
(8, 'images/Products/Men/8_1.jpg'),
(8, 'images/Products/Men/8_2.jpg'),
(8, 'images/Products/Men/8_3.jpg'),
(9, 'images/Products/Men/9_1.jpg'),
(9, 'images/Products/Men/9_2.jpg'),
(9, 'images/Products/Men/9_3.jpg'),
(10, 'images/Products/Men/10_1.jpg'),
(10, 'images/Products/Men/10_2.jpg'),
(10, 'images/Products/Men/10_3.jpg'),
(11, 'images/Products/Men/11_1.jpg'),
(11, 'images/Products/Men/11_2.jpg'),
(11, 'images/Products/Men/11_3.jpg'),
(12, 'images/Products/Men/12_1.jpg'),
(12, 'images/Products/Men/12_2.jpg'),
(12, 'images/Products/Men/12_3.jpg'),
(13, 'images/Products/Men/13_1.jpg'),
(13, 'images/Products/Men/13_2.jpg'),
(13, 'images/Products/Men/13_3.jpg'),
(14, 'images/Products/Men/14_1.jpg'),
(14, 'images/Products/Men/14_2.jpg'),
(14, 'images/Products/Men/14_3.jpg'),
(15, 'images/Products/Men/15_1.jpg'),
(15, 'images/Products/Men/15_2.jpg'),
(15, 'images/Products/Men/15_3.jpg'),
(16, 'images/Products/Men/16_1.jpg'),
(16, 'images/Products/Men/16_2.jpg'),
(16, 'images/Products/Men/16_3.jpg'),
(17, 'images/Products/Men/17_1.jpg'),
(17, 'images/Products/Men/17_2.jpg'),
(17, 'images/Products/Men/17_3.jpg'),
(18, 'images/Products/Men/18_1.jpg'),
(18, 'images/Products/Men/18_2.jpg'),
(18, 'images/Products/Men/18_3.jpg'),
(19, 'images/Products/Men/19_1.jpg'),
(19, 'images/Products/Men/19_2.jpg'),
(19, 'images/Products/Men/19_3.jpg'),
(20, 'images/Products/Men/20_1.jpg'),
(20, 'images/Products/Men/20_2.jpg'),
(20, 'images/Products/Men/20_3.jpg'),

--Images of product women details 
(21, 'images/Products/Women/1_1.jpg'),
(21, 'images/Products/Women/1_2.jpg'),
(21, 'images/Products/Women/1_3.jpg'),
(22, 'images/Products/Women/2_1.jpg'),
(22, 'images/Products/Women/2_2.jpg'),
(22, 'images/Products/Women/2_3.jpg'),
(23, 'images/Products/Women/3_1.jpg'),
(23, 'images/Products/Women/3_2.jpg'),
(23, 'images/Products/Women/3_3.jpg'),
(24, 'images/Products/Women/4_1.jpg'),
(24, 'images/Products/Women/4_2.jpg'),
(24, 'images/Products/Women/4_3.jpg'),
(25, 'images/Products/Women/5_1.jpg'),
(25, 'images/Products/Women/5_2.jpg'),
(25, 'images/Products/Women/5_3.jpg'),
(26, 'images/Products/Women/6_1.jpg'),
(26, 'images/Products/Women/6_2.jpg'),
(26, 'images/Products/Women/6_3.jpg'),
(27, 'images/Products/Women/7_1.jpg'),
(27, 'images/Products/Women/7_2.jpg'),
(27, 'images/Products/Women/7_3.jpg'),
(28, 'images/Products/Women/8_1.jpg'),
(28, 'images/Products/Women/8_2.jpg'),
(28, 'images/Products/Women/8_3.jpg'),
(29, 'images/Products/Women/9_1.jpg'),
(29, 'images/Products/Women/9_2.jpg'),
(29, 'images/Products/Women/9_3.jpg'),
(30, 'images/Products/Women/10_1.jpg'),
(30, 'images/Products/Women/10_2.jpg'),
(30, 'images/Products/Women/10_3.jpg'),
(31, 'images/Products/Women/11_1.jpg'),
(31, 'images/Products/Women/11_2.jpg'),
(31, 'images/Products/Women/11_3.jpg'),
(32, 'images/Products/Women/12_1.jpg'),
(32, 'images/Products/Women/12_2.jpg'),
(32, 'images/Products/Women/12_3.jpg'),
(33, 'images/Products/Women/13_1.jpg'),
(33, 'images/Products/Women/13_2.jpg'),
(33, 'images/Products/Women/13_3.jpg'),
(34, 'images/Products/Women/14_1.jpg'),
(34, 'images/Products/Women/14_2.jpg'),
(34, 'images/Products/Women/14_3.jpg'),
(35, 'images/Products/Women/15_1.jpg'),
(35, 'images/Products/Women/15_2.jpg'),
(35, 'images/Products/Women/15_3.jpg'),
(36, 'images/Products/Women/16_1.jpg'),
(36, 'images/Products/Women/16_2.jpg'),
(36, 'images/Products/Women/16_3.jpg'),
(37, 'images/Products/Women/17_1.jpg'),
(37, 'images/Products/Women/17_2.jpg'),
(37, 'images/Products/Women/17_3.jpg'),
(38, 'images/Products/Women/18_1.jpg'),
(38, 'images/Products/Women/18_2.jpg'),
(38, 'images/Products/Women/18_3.jpg'),
(39, 'images/Products/Women/19_1.jpg'),
(39, 'images/Products/Women/19_2.jpg'),
(39, 'images/Products/Women/19_3.jpg'),
(40, 'images/Products/Women/20_1.jpg'),
(40, 'images/Products/Women/20_2.jpg'),
(40, 'images/Products/Women/20_3.jpg'),

--Images of product unisex details 
(41, 'images/Products/Unisex/1_1.jpg'),
(41, 'images/Products/Unisex/1_2.jpg'),
(41, 'images/Products/Unisex/1_3.jpg'),
(42, 'images/Products/Unisex/2_1.jpg'),
(42, 'images/Products/Unisex/2_2.jpg'),
(42, 'images/Products/Unisex/2_3.jpg'),
(43, 'images/Products/Unisex/3_1.jpg'),
(43, 'images/Products/Unisex/3_2.jpg'),
(43, 'images/Products/Unisex/3_3.jpg'),
(44, 'images/Products/Unisex/4_1.jpg'),
(44, 'images/Products/Unisex/4_2.jpg'),
(44, 'images/Products/Unisex/4_3.jpg'),
(45, 'images/Products/Unisex/5_1.jpg'),
(45, 'images/Products/Unisex/5_2.jpg'),
(45, 'images/Products/Unisex/5_3.jpg'),
(46, 'images/Products/Unisex/6_1.jpg'),
(46, 'images/Products/Unisex/6_2.jpg'),
(46, 'images/Products/Unisex/6_3.jpg'),
(47, 'images/Products/Unisex/7_1.jpg'),
(47, 'images/Products/Unisex/7_2.jpg'),
(47, 'images/Products/Unisex/7_3.jpg'),
(48, 'images/Products/Unisex/8_1.jpg'),
(48, 'images/Products/Unisex/8_2.jpg'),
(48, 'images/Products/Unisex/8_3.jpg'),
(49, 'images/Products/Unisex/9_1.jpg'),
(49, 'images/Products/Unisex/9_2.jpg'),
(49, 'images/Products/Unisex/9_3.jpg'),
(50, 'images/Products/Unisex/10_1.jpg'),
(50, 'images/Products/Unisex/10_2.jpg'),
(50, 'images/Products/Unisex/10_3.jpg'),
(51, 'images/Products/Unisex/11_1.jpg'),
(51, 'images/Products/Unisex/11_2.jpg'),
(51, 'images/Products/Unisex/11_3.jpg'),
(52, 'images/Products/Unisex/12_1.jpg'),
(52, 'images/Products/Unisex/12_2.jpg'),
(52, 'images/Products/Unisex/12_3.jpg'),
(53, 'images/Products/Unisex/13_1.jpg'),
(53, 'images/Products/Unisex/13_2.jpg'),
(53, 'images/Products/Unisex/13_3.jpg'),
(54, 'images/Products/Unisex/14_1.jpg'),
(54, 'images/Products/Unisex/14_2.jpg'),
(54, 'images/Products/Unisex/14_3.jpg'),
(55, 'images/Products/Unisex/15_1.jpg'),
(55, 'images/Products/Unisex/15_2.jpg'),
(55, 'images/Products/Unisex/15_3.jpg'),
(56, 'images/Products/Unisex/16_1.jpg'),
(56, 'images/Products/Unisex/16_2.jpg'),
(56, 'images/Products/Unisex/16_3.jpg'),
(57, 'images/Products/Unisex/17_1.jpg'),
(57, 'images/Products/Unisex/17_2.jpg'),
(57, 'images/Products/Unisex/17_3.jpg'),
(58, 'images/Products/Unisex/18_1.jpg'),
(58, 'images/Products/Unisex/18_2.jpg'),
(58, 'images/Products/Unisex/18_3.jpg'),
(59, 'images/Products/Unisex/19_1.jpg'),
(59, 'images/Products/Unisex/19_2.jpg'),
(59, 'images/Products/Unisex/19_3.jpg'),
(60, 'images/Products/Unisex/20_1.jpg'),
(60, 'images/Products/Unisex/20_2.jpg'),
(60, 'images/Products/Unisex/20_3.jpg'),

--Images of product giftset details 
(61, 'images/Products/Giftset/1_1.jpg'),
(61, 'images/Products/Giftset/1_2.jpg'),
(61, 'images/Products/Giftset/1_3.jpg'),
(62, 'images/Products/Giftset/2_1.jpg'),
(62, 'images/Products/Giftset/2_2.jpg'),
(62, 'images/Products/Giftset/2_3.jpg'),
(63, 'images/Products/Giftset/3_1.jpg'),
(63, 'images/Products/Giftset/3_2.jpg'),
(63, 'images/Products/Giftset/3_3.jpg'),
(64, 'images/Products/Giftset/4_1.jpg'),
(64, 'images/Products/Giftset/4_2.jpg'),
(64, 'images/Products/Giftset/4_3.jpg'),
(65, 'images/Products/Giftset/5_1.jpg'),
(65, 'images/Products/Giftset/5_2.jpg'),
(65, 'images/Products/Giftset/5_3.jpg');

CREATE TABLE [dbo].[Cart] (
    CartID INT PRIMARY KEY IDENTITY(1,1),
    ProductFullDetailID INT NOT NULL,
    Quantity INT NOT NULL,
    CreateDate DATE NOT NULL,
    TotalPrice FLOAT NOT NULL,
    FOREIGN KEY (ProductFullDetailID) REFERENCES [dbo].[ProductFullDetail]([ProductFullDetailID]),
)


CREATE TABLE [dbo].[StatusOrder] (
    SOID INT PRIMARY KEY IDENTITY(1,1),
    SOName NVARCHAR(255) NOT NULL,
    SOStatus INT NOT NULL
)



CREATE TABLE [dbo].[Orders] (
    OrderID INT PRIMARY KEY IDENTITY(1,1),
    AccountID INT NOT NULL,
    OrderDate DATE NOT NULL,
    OrderTotalPrice FLOAT NOT NULL,
    OrderContactName NVARCHAR(255) NOT NULL,
    OrderPhone NVARCHAR(255) NOT NULL,
    OrderAddress NVARCHAR(255) NOT NULL,
    OrderStatus INT NOT NULL,
    OrderReceiveDate DATE NULL,
    OrderNote NVARCHAR(255) NULL,
    OrderSoID INT NOT NULL,
    FOREIGN KEY (AccountID) REFERENCES [dbo].[Accounts](AccountID),
    FOREIGN KEY (OrderSoID) REFERENCES [dbo].[StatusOrder](SOID)
)
CREATE TABLE [dbo].[OrderDetail] (
    odID INT PRIMARY KEY IDENTITY(1,1),
    odOrderID INT NOT NULL,
    odProductID INT NOT NULL,
    odQuantity INT NOT NULL,
    odPrice FLOAT NOT NULL,
    FOREIGN KEY (odOrderID) REFERENCES [dbo].[Orders](OrderID),
    FOREIGN KEY (odProductID) REFERENCES [dbo].[Products](ProductID)
)
CREATE TABLE [dbo].[Sliders](
[SliderID] int PRIMARY KEY IDENTITY(1,1),
[SliderImage] nvarchar(255) NOT NULL,
[SliderStatus] bit NOT NULL,
[SliderTitle] nvarchar(max) NULL,
)
INSERT INTO [dbo].[Sliders] ([SliderImage],[SliderTitle],[SliderStatus])
VALUES
('images/Sliders/slider1.jpg',NULL,1),
('images/Sliders/2.jpg',NULL,1),
('images/Sliders/3.jpg',NULL,1)